### ISSUE TITLE
Why the results of EDM are so bad?

### ISSUE THREAD

**Issue by yuanzhi-zhu** [mehranagh20/AdaIMLE#1]
Thank you for your great work!

I would like to know what make the results of EDM so bad in your paper, especially the distortions in generated images.

Is it caused merely by the small size of training set?

Would like to know more details on the experiments :)

**Comment by mehranagh20** [comment]
Thanks @yuanzhi-zhu.
Yes, we attribute those distortions to having very few data examples (~100). Those distortions are consistent across all datasets.
I think there needs to be a more specific study on why this happens since the distortions are pretty interesting. They are not noisy, the model has learnt to generate different parts of images (such as eyes) but fails to produce consistent structure.

**Comment by yuanzhi-zhu** [comment]
@mehranagh20 Thanks for your reply.
Could you please tell me the experiment setup to reproduce these EDM results?

**Comment by mehranagh20** [comment]
We used the same setup explained in their GitHub repo. You can take a look here: https://github.com/NVlabs/edm#training-new-models

**Comment by yuanzhi-zhu** [comment]
that's cool, thanks!!
